### ISSUE TITLE
Swift 4 and Foundation - New block-based KVO

### ISSUE THREAD

**Issue by TofPlay** [ole/whats-new-in-swift-4#6]
Hi,
With the WWDC 2017 in session 201 [What's New in Cocoa Touch](https://developer.apple.com/videos/play/wwdc2017/201/) (21m01) Apple introduce a new block-base KVO. 
Is not a pure Swift 4 feature 🤔  but it's may be interesting to mention on your playground 😉
![swift 4 and foundation - new block-based kvo](https://user-images.githubusercontent.com/1082222/27323613-6a2fac9c-55a2-11e7-83a2-c137c7450729.png)

**Comment by ole** [comment]
Thanks for the suggestion. I’ll consider adding an example.

**Comment by ole** [comment]
I added a KVO example.

**Comment by TofPlay** [comment]
In which section did you add the example?
I can not find it..

**Comment by ole** [comment]
On the key paths page, at the bottom. https://github.com/ole/whats-new-in-swift-4/blob/master/Whats-new-in-Swift-4.playground/Pages/Key%20paths.xcplaygroundpage/Contents.swift#L53-L95

**Comment by TofPlay** [comment]
Ok 🙂
