### ISSUE TITLE
Associated type constraints page broken by Xcode 9b3

### ISSUE THREAD

**Issue by rcritz** [ole/whats-new-in-swift-4#8]
I haven't had time to dig into exactly what's wrong but the associated type constraints page no longer compiles with Xcode 9 beta 3.

**Comment by ole** [comment]
Thanks. I actually made a mistake there, assuming that [SE-0157, recursive protocol constraints](https://github.com/apple/swift-evolution/blob/master/proposals/0157-recursive-protocol-constraints.md) had been implemented when in fact that proposal is probably not going to make the cut for Swift 4. In hindsight I don't quite understand why my code used to work in earlier betas, but that was probably a fluke.

I have to come up with a different example. I'll probably push an update tomorrow.

**Comment by ole** [comment]
Fixed in 23da445fe8417263ed114ad9ac8dd4e73682da71.
