### ISSUE TITLE
integer-protocols.png is not displaying

### ISSUE THREAD

**Issue by rcritz** [ole/whats-new-in-swift-4#9]
integer-protocols.png, referenced by the "New Integer Protocols" page is not displaying. I spent a few minutes trying tweaking the resource in the page but nothing causes it to display. I see it in the `Resources` folder. Is this just an Xcode 9 bug?

**Comment by ole** [comment]
Yes, I’m pretty sure it’s a bug in Xcode 9b3. The image is visible in Xcode 8.3. I filed a bug with Apple yesterday.

**Comment by ole** [comment]
This has been fixed in Xcode 9b4, released today.
